### ISSUE TITLE
Already running sbot

### ISSUE THREAD

**Issue by stoically** [talenet/talenet#5]
Host: Ubuntu 16.04.3 LTS, Linux pc 4.4.0-109-generic #132-Ubuntu SMP x86_64
Talenet: deb, 0.9.0-alpha.2-8 amd64

Hi,

if you already have a sbot running (e.g. with Patchwork), talenet will start but show something like this on the pull:ideas page:

![image](https://user-images.githubusercontent.com/29637501/35081684-d142321e-fc15-11e7-8a52-752c958085e2.png)

[According to cryptix](https://viewer.scuttlebot.io/%25YxraFc1X%2FVVdkkhO4KmSMAJyZS1fdMInIpG9NSjNN7s%3D.sha256) the `-g` parameter should use the already running sbot - but starting `talenet -g` with the latest alpha2 release shows the same behavior: empty idea descriptions.

When clicking pull:ideas the devtools console shows
```
/opt/talenet/resources/app.asar/node_modules/bluebird/js/release/debuggability.js:873 [31mUnhandled rejection Error: no source:talequery,read
    at Object.localCall (/tmp/.mount_PatchwSV30YM/app/resources/app.asar/node_modules/muxrpc/local-api.js:29:13)
    at Object.<anonymous> (/tmp/.mount_PatchwSV30YM/app/resources/app.asar/node_modules/muxrpc/local-api.js:37:22)
    at PacketStreamSubstream.stream.read (/tmp/.mount_PatchwSV30YM/app/resources/app.asar/node_modules/muxrpc/stream.js:67:23)
    at PacketStream._onstream (/tmp/.mount_PatchwSV30YM/app/resources/app.asar/node_modules/packet-stream/index.js:230:11)
    at PacketStream.write (/tmp/.mount_PatchwSV30YM/app/resources/app.asar/node_modules/packet-stream/index.js:135:41)
    at /tmp/.mount_PatchwSV30YM/app/resources/app.asar/node_modules/muxrpc/pull-weird.js:56:15
    at /tmp/.mount_PatchwSV30YM/app/resources/app.asar/node_modules/pull-stream/sinks/drain.js:24:37
    at /tmp/.mount_PatchwSV30YM/app/resources/app.asar/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/tmp/.mount_PatchwSV30YM/app/resources/app.asar/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/tmp/.mount_PatchwSV30YM/app/resources/app.asar/node_modules/pull-reader/index.js:39:14)[0m
``` 

It would also be nice if talenet could detect an already running sbot and automatically fallback to not start its own but use the already running one.

If I'm missing something or if I can provide more informations, please let me know.

**Comment by cryptix** [comment]
Hey @stoically! Thanks for trying and reporting your findings!

Obviously we have to work on our error escalation.. You should have gotten this message:

![tale-error](https://user-images.githubusercontent.com/111202/35098477-9f54a374-fc54-11e7-919c-055c0aa87251.png)
(which is also badly styled for some reason..? @baldo @luroc)

also: the required plugin is called `ssb-talequery`.. 😅 I also replied to the thread you mentioned erlier with more info.

**Comment by cryptix** [comment]
regarding the sbot connection establishment: running the AppImage or the `talenet` command from the debian image with `-g` should give the desired effect of using another sbot... we definetly need to update the README in our repo..

I tried to test for a running sbot automatically so nobody has to worry about this [in the past](https://github.com/talenet/talenet/blob/master/index.js#L141). At the time it was abit of a hassle but now that ssbc/muxrpc#37 is merged it might be easier to pull this off. Patchwork could benefit from this too, I think.

**Comment by stoically** [comment]
Thanks for the fast response and clarification!

I guess this is more of a scuttlebot problem, but running `sbot plugins.install ssb-talequery` gives me
```
Command not found: plugins.install
```

And I agree, every scuttlebutt client could benefit from having an already running sbot detection/handling.

**Comment by cryptix** [comment]
Aahh.. sigh.. I forgot that the sbot embedded in patchwork [doesn't have](https://github.com/ssbc/patchwork/blob/master/server-process.js) the plugin to install other [3rd party plugins](https://github.com/ssbc/scuttlebot/blob/master/bin.js#L57).. Getting all this straightend out will require some coordinated effort... cc @mmckegg @mixmix

**Comment by mixmix** [comment]
On holiday, back soon

**Comment by mmckegg** [comment]
I think this is the way forward: https://github.com/ssbc/patchwork/issues/686

**Comment by mixmix** [comment]
I was thinking about sbot plugins being another depject collector. Reduce
the plugins down, then use them all as you start your sbot

**Comment by baldo** [comment]
As we have to issues at hand I've created a separate issue (#7) for the error handling bug within tale:net. I'll tag this issue as a "question" for discussing the sbot aspect.

**Comment by cryptix** [comment]
There also seems to be a regression with the plugin detection:

From beta1 running against sbot
```
/tmp/.mount_taleneK5yiv2/app/resources/app.asar/node_modules/bluebird/js/release/debuggability.js:873

[31mUnhandled rejection Error: no source:talequery,read
    at Object.localCall (/home/user/ssb-projects/scuttlebot/node_modules/muxrpc/local-api.js:29:13)
    at Object.<anonymous> (/home/user/ssb-projects/scuttlebot/node_modules/muxrpc/local-api.js:37:22)
    at PacketStreamSubstream.stream.read (/home/user/ssb-projects/scuttlebot/node_modules/muxrpc/stream.js:67:23)
    at PacketStream._onstream (/home/user/ssb-projects/scuttlebot/node_modules/packet-stream/index.js:228:11)
    at PacketStream.write (/home/user/ssb-projects/scuttlebot/node_modules/packet-stream/index.js:135:41)
    at /home/user/ssb-projects/scuttlebot/node_modules/muxrpc/pull-weird.js:56:15
    at /home/user/ssb-projects/scuttlebot/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/user/ssb-projects/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/user/ssb-projects/scuttlebot/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/home/user/ssb-projects/scuttlebot/node_modules/pull-reader/index.js:39:14)[0m

printWarning @ /tmp/.mount_taleneK5yiv2/app/resources/app.asar/node_modules/bluebird/js/release/debuggability.js:873
formatAndLogError @ /tmp/.mount_taleneK5yiv2/app/resources/app.asar/node_modules/bluebird/js/release/debuggability.js:593
fireRejectionEvent @ /tmp/.mount_taleneK5yiv2/app/resources/app.asar/node_modules/bluebird/js/release/debuggability.js:618
Promise._notifyUnhandledRejection @ /tmp/.mount_taleneK5yiv2/app/resources/app.asar/node_modules/bluebird/js/release/debuggability.js:64
(anonymous) @ /tmp/.mount_taleneK5yiv2/app/resources/app.asar/node_modules/bluebird/js/release/debuggability.js:43
```
